# Generated by Django 5.2.6 on 2025-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней авторизации'),
        ),
    ]
