# Generated by Django 5.2.6 on 2025-10-15 16:32

from django.db import migrations


def add_creators_as_admins(apps, schema_editor):
    """Добавляет создателей проектов как администраторов"""
    Project = apps.get_model('testcases', 'Project')
    ProjectMember = apps.get_model('testcases', 'ProjectMember')
    
    for project in Project.objects.all():
        # Создаем запись ProjectMember для создателя проекта
        ProjectMember.objects.get_or_create(
            project=project,
            user=project.created_by,
            defaults={
                'role': 'admin',
                'added_by': project.created_by
            }
        )


def reverse_add_creators_as_admins(apps, schema_editor):
    """Обратная операция - удаляет записи ProjectMember"""
    ProjectMember = apps.get_model('testcases', 'ProjectMember')
    ProjectMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_projectmember'),
    ]

    operations = [
        migrations.RunPython(
            add_creators_as_admins,
            reverse_add_creators_as_admins
        ),
    ]
